### ISSUE TITLE
A possible issue with multi-line node values

### ISSUE THREAD

**Issue by pidgeon777** [crypto-rsa/XmlNavigator#7]
If a node with multi-line content is encountered, the subsequent treeview items position are not correctly computed. Example: clicking on the nodes in the treeview following the **Formula** tag doesn't place the cursor at the correct locations (and node/content selection gets also broken):

![0tzyiidmjv](https://user-images.githubusercontent.com/13739892/51479774-92af4680-1d8f-11e9-89ff-e5d4f551cc2e.gif)

**Comment by crypto-rsa** [comment]
Did you edit the file manually? Are you sure the treeview has been refreshed since the last change? It is enough to switch to a different file within Notepad++ and then back.

**Comment by pidgeon777** [comment]
Hi, I tried again and now it seems to work. Eventually, I'll re-open this issue if the problem arises again.
